---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeter
  labels:
    app: greeter
spec:
  selector:
    # to avoid missing label selectors use YAML aliases
    matchLabels:
      app: greeter
  template:
    metadata:
      labels:
        app: greeter
      annotations:
        last-deployment-timestamp: {{ now | unixEpoch | quote }}
    spec:
      containers:
        - name: greeter
          image: {{ .Values.image }}
          imagePullPolicy: Always
          resources:
            limits:
              memory: "750Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
